### ISSUE TITLE
'DocuSign-iOS-SDK/DocuSign-iOS-SDK.h' file not found

### ISSUE THREAD

**Issue by kwerle** [docusign/docusign-ios-sdk#4]
I'm trying to use the DocuSign SDK in a mixed ObjC/Swift app.  as it happens, I'm trying to use it form an ObjC file - and it's not finding the header.

When I create a new ObjC project it 'just works' - at least as far as compiling.  Is there something special we need to do [with the pod] to get it to work in a mixed language project?

**Comment by mikebz** [comment]
Hi there!  I don't think we have tried using the SDK with Swift.  At this point in time I am not sure we can be of any help here.  Sorry :/ if you find a solution - please share.

**Comment by adamcjohnson** [comment]
Having the same issue. @kwerle were you ever able to find a solution?

**Comment by adamcjohnson** [comment]
Strangely the Pod order seemed to affect it. I moved DocuSign pod higher in the my pod list, and the files installed properly.

**Comment by LarryKlugerDS** [comment]
Please accept my apologies for the extremely slow response to your issue.
We've now automated new processes so this won't happen again.

Meanwhile, this repo is now obsolete. Please see the README file for more information. Thank you.
