### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by vishnu-sharma** [docusign/docusign-ios-sdk#5]
I am trying to use this SDK in my iOS app. I have installed it using pod and was able to build it after importing #import <DocuSign-iOS-SDK/DocuSign-iOS-SDK.h>
When I try to use 
[[DSSessionManager alloc] initWithIntegratorKey: 
or
DSLoginViewController *loginViewController = [[DSLoginViewController alloc] initWithIntegratorKey

I am getting error  - Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DSSessionManager", referenced from:
      objc-class-ref in myClass.o

Is this SDK not compatible for 64-Bit or there is some other thing I am missing ?

**Comment by Ergin008** [comment]
Hi Vishnu, thanks for reaching out.  This repo/library is actually an older, beta SDK that will be deprecated soon.  We have a new more complete Objective-C client that can be found here: 

https://github.com/docusign/docusign-objc-client

This newer client is generated from Swagger so it has wrapper methods for most of the REST API calls across the platform (though not 100% yet).  In any case this new client definitely has the basic API scenarios covered plus a lot more so hoping you'll find this useful.  

Feel free to log issues and create pull requests on the new client if anything comes up.

Thanks,
-Ergin

**Comment by LarryKlugerDS** [comment]
Please accept my apologies for the extremely slow response to your issue.
We've now automated new processes so this won't happen again.

Meanwhile, this repo is now obsolete. Please see the README file for more information. Thank you.
