### ISSUE TITLE
when I use live docusign error found

### ISSUE THREAD

**Issue by ShabnamVarshney** [docusign/docusign-ios-sdk#6]
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1d172c30> { URL: https://www.docusign.net/restapi/v2/accounts/a6fcf1f7-58de-4f74-bb73-d6c93fb2d66c/envelopes?merge_roles_on_draft=false } { status code: 401, headers {
    "Cache-Control" = "no-cache";
    "Content-Length" = 116;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 18 Sep 2017 11:55:49 GMT";
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains";
    "X-DocuSign-TraceToken" = "d0048f6d-dd39-4988-b159-dd3503ef0fae";
} }, NSErrorFailingURLKey=https://www.docusign.net/restapi/v2/accounts/a6fcf1f7-58de-4f74-bb73-d6c93fb2d66c/envelopes?merge_roles_on_draft=false, NSLocalizedDescription=Request failed: unauthorized (401), DSResponseObject=<NSHTTPURLResponse: 0x1d172c30> { URL: https://www.docusign.net/restapi/v2/accounts/a6fcf1f7-58de-4f74-bb73-d6c93fb2d66c/envelopes?merge_roles_on_draft=false } { status code: 401, headers {
    "Cache-Control" = "no-cache";
    "Content-Length" = 116;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 18 Sep 2017 11:55:49 GMT";
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains";
    "X-DocuSign-TraceToken" = "d0048f6d-dd39-4988-b159-dd3503ef0fae";
} }, com.alamofire.serialization.response.error.data=<7b0d0a20 20226572 726f7243 6f646522 3a202255 5345525f 41555448 454e5449 43415449 4f4e5f46 41494c45 44222c0d 0a202022 6d657373 61676522 3a20224f 6e65206f 7220626f 7468206f 66205573 65726e61 6d652061 6e642050 61737377 6f726420 61726520 696e7661 6c69642e 220d0a7d>}

**Comment by ShabnamVarshney** [comment]
I dont know why I am getting this issue .It is working on demo but not working in production

**Comment by ShabnamVarshney** [comment]
please help

**Comment by LarryKlugerDS** [comment]
Please accept my apologies for the extremely slow response to your issue.
We've now automated new processes so this won't happen again.

Meanwhile, this repo is now obsolete. Please see the README file for more information. Thank you.
