### ISSUE TITLE
Lack of Information

### ISSUE THREAD

**Issue by suneelseelam** [docusign/docusign-ios-sdk#7]
Hi, Sorry to raise an issue, I have no Idea to contact you, I am using (https://github.com/docusign/docusign-ios-sdk) till date. I am getting the issue in the file (DSDrawSignatureView.m) when I try to put Signature, So I am trying to Integrate new(https://github.com/docusign/docusign-objc-client) I have no Idea to integrate if you have Idea Please share the example code. Thanks in Advance.

**Comment by LarryKlugerDS** [comment]
Please accept my apologies for the extremely slow response to your issue.
We've now automated new processes so this won't happen again.

Meanwhile, this repo is now obsolete. Please see the README file for more information. Thank you.
